### ISSUE TITLE
Plans for setting demo website afloat again?

### ISSUE THREAD

**Issue by alexis-michaud** [CoEDL/olac-visualisation-v1#1]
Hi, 
It seems that the [demo website](http://115.146.88.224/#/) for the beautiful OLAC visualiser is not responding anymore. Or has the URL changed? (Formerly: [http://go.coedl.net/OLACviz](http://go.coedl.net/OLACviz))

(Open-source, non-commercial solutions for maps would be an added bonus, of course.)

**Comment by nthieberger** [comment]
Hi Alexis,

Thanks for alerting me to the failed redirection in that URL. I've fixed it
now.

Nick

**Comment by alexis-michaud** [comment]
👍 
:heart_eyes:
